Document: listusb
Title: Debian listusb Manual
Author: <insert document author here>
Abstract: This manual describes what listusb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/listusb/listusb.sgml.gz

Format: postscript
Files: /usr/share/doc/listusb/listusb.ps.gz

Format: text
Files: /usr/share/doc/listusb/listusb.text.gz

Format: HTML
Index: /usr/share/doc/listusb/html/index.html
Files: /usr/share/doc/listusb/html/*.html
